import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Todos App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Link prefetch={false} href={"/todos"}>Todos</Link>
        <Link href={"/products"}>Products</Link>
        {children}
      </body>
    </html>
  );
}
